### ISSUE TITLE
Series A

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/partnerships#45]
We should build relationships with these organizations. I took some inspiration from FEI because their investors singlehandedly are the reason (besides the market conditions) why they were able to raise a billion in on-chain liquidity in 24 hours. 

### Hitlist

We first need to figure out what type of pitch will appeal to the following, and see if it makes sense to bring them on our cap table for the DevPool/Dollar

- [ ] Develop Pitch: Paradigm
- [ ] Develop Pitch: GnosisDAO
- [ ] Develop Pitch: GitHub/Microsoft
- [ ] Develop Pitch: Visa/MasterCard
- [ ] Develop Pitch: Coinbase Ventures
- [ ] Develop Pitch: a16z Crypto
- [ ] Develop Pitch: Framework Ventures
- [ ] Develop Pitch: Variant
- [ ] Develop Pitch: ParaFi
- [ ] Develop Pitch: Naval Ravikant

### Schedule
Six Months: March 2024 - September 2024
### Terms
- 10% at $100M - $200M USD valuation
  - Previously 10% at $20M USD valuation
### Milestones
These could help us with increasing our valuation.
- [ ] Ubiquity Dollar launch with collateral
- [x] https://github.com/ubiquity/research/issues/2
- [x] https://github.com/ubiquity/research/issues/6
- [ ] The launch of UbiquiCards

### Appendix

- [x] https://github.com/ubiquity/research/issues/3
