### ISSUE TITLE
GitHub Universe 2024

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/partnerships#82]
## Main Events 

| Dates | Event |
|--------|--------|
| October 18–20 | ETHGlobal San Francisco  |
| October 29-30 | [GitHub Universe](https://githubuniverse.com/ ) | 
| October 30-31 | Palo Alto AI x Web3 Summit |

**Comment by 0x4007** [comment]
Parents in Seattle 14-17th. I don't want to be in the states for so long but not sure what else to do

**Comment by ana-0k** [comment]
- Accommodation
- Flights
- Tickets to main events
- Research/register for side events

------------------------------


**Schedule suggestion:**
| Date  | Description |
| --- | --- |
| Oct 26, Sat  | Seoul > SF |
| Oct 27, Sun  | Shop iPhone |
| Oct 29-30, Tue-Wed  | GitHub Universe |
| Oct 31, Thu  | Palo Alto AI x Web3 Summit |
| Oct 31, Thu  | Halloween Party (TBC) |
| Nov 2-3, Sat-Sun  | SF > Sonoma car, wineries (w/Michael?) |
| Nov 3, Sun  | SF > Chicago OR Seoul, late flight |



**Task List:**

- [x] 1. Book flights Alex: SL>SF>CHI

- [x] 2. Book flights Ana: SL>SF>SL

- [x] 3. Book hotel SF, Oct 26 - Nov 2

- [x] 4. Book hotel Sonoma, Nov 2 - Nov 3

- [x] 5. [Buy GitHub Universe ticket x1](https://reg.githubuniverse.com/flow/github/universe24/Registration/login)

- [x] 6. [Register for AI x web3 Summit](https://www.aw3.ai/event/add12af4-e9ae-45a9-a1a8-b9c4232a00f2/regProcessStep1)


[**VENUE MAP GOOGLE**](https://maps.app.goo.gl/zasUp9DE7y93BbX16)


------------------------------
**[GitHub Universe](https://githubuniverse.com)**, Oct 29, Tue - Oct 30, Wed
No networking event links, need to buy official tickets to network.

- **Tickets** ($1,299 only optimal option): https://githubuniverse.com/#tickets

- **Schedule:** [link](https://reg.githubuniverse.com/flow/github/universe24/attendee-portal/page/sessioncatalog?tab.day=20241029)

-------------------------------
**[Palo Alto AI x Web3 Summit](https://www.aw3.ai/event/add12af4-e9ae-45a9-a1a8-b9c4232a00f2/summary)**, Oct 30-31
Looks small and niche, maybe targeted to students as the venue is in Stanford campus.
Idk the hosts, their websites are a bit sus. But maybe it's just me.
A few potentially interesting speakers.

- **Hosts:**
CTH Group (global blockchain ecosystem builder) - https://www.cth.group
MetaEra (Web3 news, HongKong) - https://www.metaera.hk

- **Tickets:** [link](https://www.aw3.ai/event/add12af4-e9ae-45a9-a1a8-b9c4232a00f2/regProcessStep1)
Free, need to get approved by the host.
I applied as a trial, will let u know if I get approved or not

**Comment by 0x4007** [comment]
@gentlementlegen heads up we started planning for GitHub Universe in case you've got inputs.

Some remarks:

- We can go to wine country as its in the area
- Consider Halloween plans, not sure where is good to celebrate but SF is probably the worst place to party that I can think of
- I wanna get an American iPhone 16, I wonder if theres any other products worth picking up while there.

Checking if I can see family after Halloween now.

**Comment by ana-0k** [comment]
A few other potentially interesting side events in SF during the trip.


**Side events for [TechCrunch Disrupt 2024](https://techcrunch.com/events/tc-disrupt-2024/)**, Oct 28-30
_Huge conference for founders and VSc in tech, not web3-related but has AI and Fintech topics. [Tickets](https://techcrunch.com/events/tc-disrupt-2024/tickets/) start from $225
Seems like side events don't require a ticket to the main event._
- Oct 29, Tue 6pm: [**TechCrunch Disrupt 2024 Official Afterparty - For Founders & Investors**](https://lu.ma/l0ac2eyx)
- Oct 30, Wed 6pm: [**Founder Friends in SF #Disrupt2024**](https://lu.ma/FFSFDisruptWeek)

**Other**
- Oct 30, Wed 10am: [**AI Hackathon with NVIDIA**](https://lu.ma/nhnos3l3) - may be able to find some AI coders here?

_None or NA for November events list yet_

**Comment by 0x4007** [comment]
Maybe just side events then

**Comment by 0x4007** [comment]
November 3rd-ish I think I will do Seattle.

**Comment by ana-0k** [comment]
@0x4007 time to close
